[package]
name = "hash-cracker"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.16.0" 
sha2 = "0.10.8"
hex-literal = "0.4.1"
rayon = "1.10.0"
lazy_static = "1.5.0"
clap = { version = "4.5.28", features = ["derive"] }